### ISSUE TITLE
AAMP root nodes

### ISSUE THREAD

**Issue by Zer0XoL** [zephenryus/botw-tools#3]
Just wanted to tell you ive figured out more than what is publically known about the AAMP format.
Check out my repository "aampTool".
Maybe you can update your writeup of aamp with this.

Thanks.

//ZerQ

**Comment by Zer0XoL** [comment]
Btw, are you aware of the botw modding hub discord server?
https://discord.gg/K47PrU

**Comment by zephenryus** [comment]
Awesome. I'm looking over it. I will also jump on discord.
